version: '3'

services:
  db:
    command: -c fsync=off # Required to use psql command in WSL
    image: postgres:11
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - db:/var/lib/postgresql/data:delegated
    ports:
      - 15432:5432
  data:
    image: busybox
    volumes:
      - db:/var/lib/postgresql/data:delegated

volumes:
  db:
    driver: local
